### PR TITLE
Added span support

### PR DESCRIPTION
**Pull request by pwiens**
Adding an additional target framework (netcoreapp2.1) and support for Span<T>

### CODE REVIEW

**Comment by dazinator** [comment]
Fantastic, thank you very much for this PR.

**Comment by dazinator** [comment]
Thanks for the PR

**Comment by pwiens** [comment]
Thanks for merging it. I'll be on the lookout of a new nuget package.

**Comment by dazinator** [comment]
https://www.nuget.org/packages/DotNet.Glob/3.0.0-alpha0045

I'll wait a while before I merge to master, which will produce a stable 3.0.0 package, so it's just on pre-release channel for now

**Pull request merged**
