### PR TITLE
Migration to csproj as well as minor changes

### PR DESCRIPTION
**Pull request by Genbox**
The namespace stuff might seem like a lot, but it is really just Resharper refactorings done automatically. I did not change the namespace in the main DotNet.Glob project to keep backward compatibility.

This pull request should also make the projects build successfully again.

### CODE REVIEW

**Comment by dazinator** [comment]
Thanks for this, I will take a look. As you can probably tell, my resharper licence expired and I have been seeing how I manage without it :-)

**Comment by dazinator** [comment]
FWIW , the reason I ended up using `DotNet.Globbing` rather than `DotNet.Glob` as the namespace was because when you attempt to do `new Glob()` it was conflicting with the namespace. I decided to amend the namespace to workaround that, but I appreciate it's a little odd that the namespace is now different from the assembly name.

**Comment by Genbox** [comment]
You can request a free Resharper license at Jetbrains since you have an open source project. The namespace refactoring has been included since VS2015 though. I can also recommend [VS Refactoring Essentials](http://vsrefactoringessentials.com/).

**Comment by dazinator** [comment]
> The namespace refactoring has been included since VS2015 though 

Is that at a project level? Project level namespace refactoring is the one I can't seem to find. I'll check out that extension - looks useful!

I've checked this out and taken a look, in general it LGTM so thanks!

I decided to tack on a few extra commits, I've removed the other glob library, and it's unit test - it's nothing really to do with this solution I was just experimenting with it to compare some features.

I've also downgraded an MS tests nugget package to a stable version as it was on a preview version.

I'll get his merged shortly.

Thanks for contributing!

**Comment by Genbox** [comment]
No problem at all. Happy you found it useful!

**Pull request merged**
